import org.jetbrains.kotlin.gradle.plugin.AndroidGradlePluginVersion

/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin library project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.5.1/userguide/building_java_projects.html in the Gradle documentation.
 */

version = "1.0.0"

plugins {
    // Apply the org.jetbrains.kotlin.jvm Plugin to add support for Kotlin.
    alias(libs.plugins.kotlin.jvm)

    // Apply the java-library plugin for API and implementation separation.
    `java-library`

    kotlin("plugin.serialization") version "2.3.20"

    id("com.vanniktech.maven.publish") version "0.36.0"
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    implementation("io.ktor:ktor-client-core:3.5.0")
    implementation("io.ktor:ktor-client-cio:3.5.0")
    implementation("io.ktor:ktor-client-resources:3.5.0")
    implementation("io.ktor:ktor-client-content-negotiation:3.5.0")
    implementation("io.ktor:ktor-serialization-kotlinx-json:3.5.0")
    implementation("io.ktor:ktor-client-logging:3.5.0")
    
    api("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.11.0")
    api("org.jetbrains.kotlinx:kotlinx-datetime:0.8.0")
    
    // Use JUnit Jupiter for testing.
    testImplementation(libs.junit.jupiter)
    testImplementation("org.jetbrains.kotlinx:kotlinx-coroutines-test:1.11.0")
    testImplementation("ch.qos.logback:logback-classic:1.5.34")

    testRuntimeOnly("org.junit.platform:junit-platform-launcher")
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

kotlin {
    explicitApi()
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}

mavenPublishing {
    publishToMavenCentral()

    signAllPublications()

    coordinates(group.toString(), "oseth", version.toString())

    pom {
        name = "OSETH Api Wrapper"
        description = "A api wrapper for OSETH"
        inceptionYear = "2026"
        url = "https://gitlab.com/mitsiosm/kt-oseth"
        licenses {
            license {
                name = "zlib License"
                url = "https://www.zlib.net/zlib_license.html"
                distribution = "repo"
            }
        }
        developers {
            developer {
                id = "mitsiosm"
                name = "Marios Mitsios"
                email = "xrteach@gmail.com"
                url = "https://gitlab.com/mitsiosm"
                organization = "mitsiosm"
                organizationUrl = "https://gitlab.com/mitsiosm"
            }
        }
        scm {
            url = "https://gitlab.com/mitsiosm/kt-oseth"
            connection = "scm:git:git://gitlab.com/mitsiosm/kt-oseth.git"
            developerConnection = "scm:git:ssh://git@gitlab.com:mitsiosm/kt-oseth.git"
        }
    }
}