import org.jetbrains.kotlin.gradle.dsl.JvmTarget

/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin library project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.5.1/userguide/building_java_projects.html in the Gradle documentation.
 */

version = "1.1.0"
group = "io.gitlab.mitsiosm"

plugins {
    alias(libs.plugins.android.kotlin.multiplatform.library)
    alias(libs.plugins.vanniktech.mavenPublish)
    alias(libs.plugins.kotlinMultiplatform)

    kotlin("plugin.serialization") version "2.2.20"
}

//repositories {
    // Use Maven Central for resolving dependencies.
//    mavenCentral()
//}

//dependencies {
    // Use JUnit Jupiter for testing.

//    testRuntimeOnly("org.junit.platform:junit-platform-launcher")
//}

// Apply a specific Java toolchain to ease working on different environments.
//java {
//    toolchain {
//        languageVersion = JavaLanguageVersion.of(11)
//    }
//}

kotlin {
    explicitApi()
    
    jvm()

    compilerOptions {
        freeCompilerArgs.add(
            "-opt-in=kotlin.time.ExperimentalTime"
        )
    }

    androidLibrary {
        namespace = "io.gitlab.mitsiosm.oseth.library"
        compileSdk = libs.versions.android.compileSdk.get().toInt()
        minSdk = libs.versions.android.minSdk.get().toInt()

        withJava()
        withHostTestBuilder {}.configure {}
        withDeviceTestBuilder {
            sourceSetTreeName = "test"
        }

        compilerOptions {
            jvmTarget = JvmTarget.JVM_11
        }
    }

    iosArm64()
    iosSimulatorArm64()
    linuxX64()

    sourceSets {
        commonMain.dependencies {
            implementation("io.ktor:ktor-client-core:3.3.3")
            implementation("io.ktor:ktor-client-resources:3.3.3")
            implementation("io.ktor:ktor-client-content-negotiation:3.3.3")
            implementation("io.ktor:ktor-serialization-kotlinx-json:3.3.3")
            implementation("io.ktor:ktor-client-logging:3.3.3")
            implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.11.0")
            implementation("org.jetbrains.kotlinx:kotlinx-datetime:0.8.0")
        }
        
        jvmMain.dependencies {
            implementation("io.ktor:ktor-client-cio:3.3.3")
        }
        
        androidMain.dependencies {
            implementation("io.ktor:ktor-client-android:3.3.3")
        }
        
        appleMain.dependencies {
            implementation("io.ktor:ktor-client-darwin:3.3.3")
        }
        
        linuxMain.dependencies {
            implementation("io.ktor:ktor-client-curl:3.3.3")
        }

        commonTest.dependencies {
            implementation(libs.kotlin.test)
            implementation("org.jetbrains.kotlinx:kotlinx-coroutines-test:1.11.0")
            implementation("ch.qos.logback:logback-classic:1.5.34")
        }
    }
}

//tasks.named<Test>("test") {
//     Use JUnit Platform for unit tests.
//    useJUnitPlatform()
//}

mavenPublishing {
    publishToMavenCentral()

    signAllPublications()

    coordinates(group.toString(), "oseth", version.toString())

    pom {
        name = "OSETH Api Wrapper"
        description = "A api wrapper for OSETH"
        inceptionYear = "2026"
        url = "https://gitlab.com/mitsiosm/kt-oseth"
        licenses {
            license {
                name = "zlib License"
                url = "https://www.zlib.net/zlib_license.html"
                distribution = "repo"
            }
        }
        developers {
            developer {
                id = "mitsiosm"
                name = "Marios Mitsios"
                email = "xrteach@gmail.com"
                url = "https://gitlab.com/mitsiosm"
                organization = "mitsiosm"
                organizationUrl = "https://gitlab.com/mitsiosm"
            }
        }
        scm {
            url = "https://gitlab.com/mitsiosm/kt-oseth"
            connection = "scm:git:git://gitlab.com/mitsiosm/kt-oseth.git"
            developerConnection = "scm:git:ssh://git@gitlab.com:mitsiosm/kt-oseth.git"
        }
    }
}